### ISSUE TITLE
connectivity example ?

### ISSUE THREAD

**Issue by amiracam** [connamara/quickfix-jruby#2]
Hi, thanks for this , I realize that its a thin wrap on QuickFix/J but I was wondering if you have any connectivity example code that you can share.

thanks

**Comment by cbusbey** [comment]
Hi there,

We don't have specific examples in this repo, but you might find these other projects that depend on this gem as useful references:

[fix_spec](https://github.com/connamara/fix_spec) - Build and Inspection test tool for FIX Protocol messages
[agent_fix](https://github.com/connamara/agent_fix) - Agent framework designed for testing FIX Applications

**Comment by amiracam** [comment]
thank you very much

Charles Monteiro
